---
default_stages: [pre-commit, pre-push]

default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3

minimum_pre_commit_version: "3.2.0"

repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: run check hooks apply
        description: useful when testing new hooks to see if they apply to the repository
      - id: check-useless-excludes
        name: run check useless excludes
        description: check that the exclude pattern is not useless

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      - id: check-case-conflict
        name: run check for case conflicts
        description: check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT
      - id: check-illegal-windows-names
        name: run check for illegal windows names
        description: check for files that cannot be created on Windows
      - id: check-merge-conflict
        name: run check for merge conflicts
        description: check for files that contain merge conflict strings
      - id: check-yaml
        name: run check YAML
        description: attempts to load all yaml files to verify syntax
      - id: end-of-file-fixer
        name: run end of file fixer
        description: makes sure files end in a newline and only a newline
      - id: fix-byte-order-marker
        name: run fix byte order marker
        description: removes UTF-8 byte order marker
      - id: mixed-line-ending
        name: run check for mixed line endings
        description: replaces or checks mixed line ending
      - id: trailing-whitespace
        name: run check for trailing whitespace
        description: trims trailing whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8  # frozen: v2.4.3
    hooks:
      - id: codespell
        name: run codespell
        description: check for misspelled words with codespell
        args: ["--skip=git"]
